version: "3.8"

services:
  instant-ngp:
    image: marcobteixeira/instantngp:cuda10.2-u18.04
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile-v2.dockerfile
    #image: instantngp:fix
    #build:
    #  context: ..
    #  dockerfile: ./.devcontainer/Dockerfile-p2.dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - ../:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /volume
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

